version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./:/var/www
    networks:
      - laravel_network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"    # Accede a la aplicación en http://localhost:8080
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: postgres:15-alpine
    container_name: laravel_db
    environment:
      POSTGRES_DB: main_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "261121"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  pgdata:
